import {
  ClipboardText,
  ShieldCheck,
  Scissors,
  Airplane,
  Alarm,
  Anchor,
  AppleLogo,
  ArrowCircleDown,
  ArrowCircleLeft,
  ArrowCircleRight,
  ArrowCircleUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Backpack,
  Bag,
  Bank,
  Barbell,
  Basket,
  Bathtub,
  BatteryCharging,
  BatteryWarning,
  Bell,
  Book,
  Briefcase,
  Calendar,
  Camera,
  Chat,
  XLogo,
  InstagramLogo,
  FacebookLogo,
  WhatsappLogo,
  Gear,
  Ambulance,
  Asclepius,
  Bandaids,
  FirstAid,
  FirstAidKit,
  Hospital,
  Pill,
  Prescription,
  Pulse,
  Stethoscope,
  Syringe,
  FireTruck,
  GenderFemale,
  GenderMale,
  GenderNeuter,
  GenderIntersex,
  GenderTransgender,
  GenderNonbinary,
  MessengerLogo
} from '@phosphor-icons/react'
import React from 'react'

type IconComponent = React.ComponentType<React.SVGProps<SVGSVGElement>>

const iconList: { name: string; Icon: IconComponent }[] = [
  { name: 'ClipboardText', Icon: ClipboardText },
  { name: 'ShieldCheck', Icon: ShieldCheck },
  { name: 'Scissors', Icon: Scissors },
  { name: 'Airplane', Icon: Airplane },
  { name: 'Alarm', Icon: Alarm },
  { name: 'Anchor', Icon: Anchor },
  { name: 'AppleLogo', Icon: AppleLogo },
  { name: 'ArrowCircleDown', Icon: ArrowCircleDown },
  { name: 'ArrowCircleLeft', Icon: ArrowCircleLeft },
  { name: 'ArrowCircleRight', Icon: ArrowCircleRight },
  { name: 'ArrowCircleUp', Icon: ArrowCircleUp },
  { name: 'ArrowDown', Icon: ArrowDown },
  { name: 'ArrowLeft', Icon: ArrowLeft },
  { name: 'ArrowRight', Icon: ArrowRight },
  { name: 'ArrowUp', Icon: ArrowUp },
  { name: 'Backpack', Icon: Backpack },
  { name: 'Bag', Icon: Bag },
  { name: 'Bank', Icon: Bank },
  { name: 'Barbell', Icon: Barbell },
  { name: 'Basket', Icon: Basket },
  { name: 'Bathtub', Icon: Bathtub },
  { name: 'BatteryCharging', Icon: BatteryCharging },
  { name: 'BatteryWarning', Icon: BatteryWarning },
  { name: 'Bell', Icon: Bell },
  { name: 'Book', Icon: Book },
  { name: 'Briefcase', Icon: Briefcase },
  { name: 'Calendar', Icon: Calendar },
  { name: 'Camera', Icon: Camera },
  { name: 'Chat', Icon: Chat },
  { name: 'XLogo', Icon: XLogo },
  { name: 'InstagramLogo', Icon: InstagramLogo },
  { name: 'FacebookLogo', Icon: FacebookLogo },
  { name: 'WhatsappLogo', Icon: WhatsappLogo },
  { name: 'Gear', Icon: Gear },
  { name: 'Ambulance', Icon: Ambulance },
  { name: 'Asclepius', Icon: Asclepius },
  { name: 'Bandaids', Icon: Bandaids },
  { name: 'FirstAid', Icon: FirstAid },
  { name: 'FirstAidKit', Icon: FirstAidKit },
  { name: 'Hospital', Icon: Hospital },
  { name: 'Pill', Icon: Pill },
  { name: 'Prescription', Icon: Prescription },
  { name: 'Pulse', Icon: Pulse },
  { name: 'Stethoscope', Icon: Stethoscope },
  { name: 'Syringe', Icon: Syringe },
  { name: 'FireTruck', Icon: FireTruck },
  { name: 'GenderFemale', Icon: GenderFemale },
  { name: 'GenderMale', Icon: GenderMale },
  { name: 'GenderNeuter', Icon: GenderNeuter },
  { name: 'GenderIntersex', Icon: GenderIntersex },
  { name: 'GenderTransgender', Icon: GenderTransgender },
  { name: 'GenderNonbinary', Icon: GenderNonbinary },
  { name: 'MessengerLogo', Icon: MessengerLogo }
]

export default iconList
